<a href="https://colab.research.google.com/github/MuhammadRifatA/ML/blob/main/ML8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TUGAS PRAKTIKUM

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
    - Metode pra pengolahan
    - Pemilihan fitur
    - Arsitektur ANN
    - Fungsi Aktiviasi
-ANN diimplementasikan dengan menggunakan tensorflow.
-DIKERJAKAN SECARA BERKELOMPOK
-JELASKAN HASIL YANG ANDA DAPATKAN,
    - AKURASI
    - CONFUSION MATRIX
    - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

Langkah 1 - Import Library

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist


Langkah 2 - Pra-pengolahan data MNIST

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()


11490434/11490434 [==============================] - 0s 0us/step


In [3]:
x_train = x_train / 255.0
x_test = x_test / 255.0

Langkkah 3 - Buat Arsitektur ANN

In [4]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

Langkah 4 - Buat Fugsi Aktivasi

In [5]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

Langkah 5 - Latih Model ANN dan Lakukan Evaluasi Model

In [6]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2638 - accuracy: 0.9244
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1153 - accuracy: 0.9657
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0810 - accuracy: 0.9758
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0606 - accuracy: 0.9811
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0478 - accuracy: 0.9847
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0367 - accuracy: 0.9886
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0300 - accuracy: 0.9909
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0249 - accuracy: 0.9925
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0201 - accuracy: 0.9936
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.01

In [7]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0864 - accuracy: 0.9772


[0.08643531799316406, 0.9771999716758728]

Langkah 6 - Tampilkan Confusion Matrix

In [9]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = model.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 1s 4ms/step
Confusion matrix:
 tf.Tensor(
[[ 971    0    1    0    2    0    2    0    3    1]
 [   0 1122    3    1    0    0    3    0    6    0]
 [   4    2 1008    1    0    0    3    3   10    1]
 [   0    1    7  971    0   12    0    3    9    7]
 [   1    1    6    0  956    0    2    2    0   14]
 [   3    0    0    3    2  871    6    0    4    3]
 [   7    1    2    0    5    2  940    0    1    0]
 [   2    5   13    1    0    0    0  998    2    7]
 [   1    0    5    0    3    1    1    4  956    3]
 [   2    3    1    2    9    4    0    4    5  979]], shape=(10, 10), dtype=int32)
